### ISSUE TITLE
CommandGQL Integration - Basic

### ISSUE THREAD

**Issue by binarythistle** [binarythistle/DevWorkbench#8]
### Tasks

- [x] Add Endpoint as Config in User Secrets (Dev) - `httpsgraphqlcommandapi`
- [x] Add Endpoint as Config Settings (Prod) - `httpsgraphqlcommandapi`
- [x] Add Platform and Command Models
- [x] Add Data Service (Http Client)
- [x] Create .cs and .razor UI Pages

### Acceptance Criteria

Given: A user has typed in a criteria
When: User Clicks "Search"
Then: GraphQL Endpoint will be searched with that criteria
And: Results returned and displayed as line items

Card is Done when this is deployed to production

### Screen Mocks
![Search GQL API - Basic](https://user-images.githubusercontent.com/815719/110260698-61db0b80-8001-11eb-9a93-43c9ce17a525.png)
